In [1]:
import pandas as pd
import numpy as np
folder = 'd:/git/project1/generated'

In [2]:
#btc_direct_table = pd.read_csv(f'{folder}/btc_daily_change_direct.csv')
btc_direct_table = pd.read_csv(f'{folder}/bts_price_changes.csv')
btc_direct_table

,Open,High,Low,Close,Volume,change_1_day,change_3_day,change_7_day,change_14_day,change_30_day,...,direct_1,direct_3,direct_7,direct_14,direct_30,direct_60,direct_90,direct_180,change_percent_1,change_percent_180
0,465.864014,468.174011,452.421997,457.334015,2.105680e+07,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0.000000,0.000000
1,456.859985,456.859985,413.104004,424.440002,3.448320e+07,-9.004029,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,-0.021214,0.000000
2,424.102997,427.834991,384.532013,394.795990,3.791970e+07,-32.756988,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,-0.082972,0.000000
3,394.673004,423.295990,389.882996,408.903992,3.686360e+07,-29.429993,-71.191010,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,-0.071973,0.000000
4,408.084991,412.425995,393.181000,398.821014,2.658010e+07,13.411987,-48.774994,0.000000,0.000000,0.000000,...,1,0,0,0,0,0,0,0,0.033629,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,58326.562500,58937.046875,57807.863281,58245.003906,4.665521e+10,-2086.593750,-2660.960937,-2826.648437,3373.167969,3826.945313,...,0,0,0,1,1,1,1,1,-0.035824,0.773298
2396,58253.777344,61276.664063,58038.707031,59793.234375,5.823847e+10,2226.648437,-845.371094,-772.316406,6643.550781,3502.550781,...,1,0,0,1,1,1,1,1,0.037239,0.786552
2397,59846.230469,60790.554688,59289.796875,60204.964844,4.628025e+10,-72.785156,67.269531,-1143.632812,3116.210938,2290.597656,...,0,1,0,1,1,1,1,1,-0.001209,0.965382
2398,60175.945313,61253.035156,59589.875000,59893.453125,5.182869e+10,1592.453125,3746.316406,2241.390625,3871.289063,2025.011719,...,1,1,1,1,1,1,1,1,0.026588,0.810609
2399,60292.875000,63152.812500,59892.859375,62944.847656,6.289527e+10,329.714844,1849.382813,1415.070313,4228.046875,2832.574219,...,1,1,1,1,1,1,1,1,0.005238,0.774438

In [3]:
date_time_title_short = pd.read_csv(f'{folder}/date_time_title_short.csv')

In [7]:
btc_timestamps = btc_direct_table['timestamp']
#btc_direct =  btc_direct_table['direct']
btc_direct =  btc_direct_table['direct_30']
news_timestamps_all = date_time_title_short['date']

In [8]:
def get_directs(news_timestamps):
    directs = []
    for news_timestamp in news_timestamps:
        #print(ts_news)
        finded = False
        for i in range(btc_direct.shape[0]):
            if news_timestamp == btc_timestamps[i]:
                directs.append(btc_direct[i])
                finded = True
                break;
        if (not finded):
            print('not finded')
            directs.append(0)    
    return directs

In [9]:
def get_union_table(num):
    table = pd.read_csv(f'{folder}/classification_{num*1000}_{(num+1)*1000-1}.csv')
    table['timestamp'] = np.array(news_timestamps_all[num*1000:(num+1)*1000-1])
    table['direct'] = get_directs(table['timestamp'])
    return table

In [41]:
%%time
res_table = pd.DataFrame(None)
res_table = res_table.append(get_union_table(0), sort=False, ignore_index=True)
res_table

not finded
not finded
Wall time: 12.9 s

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,760,761,762,763,764,765,766,767,timestamp,direct
0,0,-0.571585,0.140949,0.060760,0.153261,-0.145271,0.115880,0.497591,0.415114,-0.482140,...,0.493163,0.115500,0.248566,-0.254553,0.296603,-0.572895,-0.096047,0.210568,1553817600,0
1,1,-0.379941,-0.027598,-0.004053,-0.293699,-0.261320,-0.360896,0.477414,0.384128,-0.080506,...,0.289536,-0.000280,0.316195,-0.265717,-0.172322,-0.388621,0.272517,0.179656,1594857600,1
2,2,-0.473415,-0.110131,0.158560,-0.018178,-0.503009,0.266457,0.501562,0.132371,-0.278618,...,0.470979,-0.206761,-0.019523,-0.423772,-0.214560,-0.261824,0.538293,0.213355,1551657600,0
3,3,-0.557469,-0.117192,-0.171127,-0.016516,-0.639803,-0.098061,0.677578,0.374796,-0.213820,...,0.149891,-0.405337,0.313279,-0.265779,0.195671,-0.648685,0.202946,0.170861,1570838400,0
4,4,-0.020235,-0.063642,-0.252436,-0.144558,-0.467133,0.015928,0.411918,0.571481,-0.618786,...,0.301235,-0.233004,0.373178,-0.012555,-0.001489,-1.000661,-0.315609,0.589265,1571011200,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,-0.903676,-0.245738,0.726553,0.291743,-0.411755,0.055630,-0.026003,0.524372,-0.458228,...,0.334878,-0.295819,0.002997,-0.012726,-0.337924,-0.398091,0.999576,-0.192687,1556668800,1
995,995,0.196535,-0.320330,-0.172901,-0.197863,-0.411071,-0.123201,0.251156,0.629572,-0.136764,...,-0.358588,-0.216856,0.356312,-0.061615,-0.149532,-0.272039,0.212401,0.475615,1575936000,0
996,996,-0.647224,0.053621,-0.335848,-0.025527,-0.375519,0.116078,0.544583,0.500701,0.153093,...,-0.092781,-0.017255,0.478655,0.022712,0.221546,-0.619328,0.009468,0.482455,1593475200,1
997,997,0.049727,-0.411959,-0.884755,0.144401,-0.725843,-0.085787,0.523452,0.114268,-0.255624,...,-0.136328,-0.154998,0.358088,0.146880,-0.496204,-0.091542,0.684666,0.765601,1596758400,1
998,998,-0.563997,-0.400995,-0.185328,-0.203333,-0.529126,-0.104635,0.574223,0.942057,0.396745,...,0.013108,-0.298138,-0.212562,0.287382,0.083733,-0.624121,0.658475,0.607768,1592179200,0

In [10]:
%%time
start = 0
for j in range(2):#max=60
    res_table = pd.DataFrame(None)#clear_table
    for i in range(10):
        num = i+j*10+start
        print(num)
        res_table = res_table.append(get_union_table(num), sort=False, ignore_index=True)
    res_table.to_csv(f'{folder}\cls_direct30_{num}.csv', index=False)

0
not finded
not finded
1
not finded
2
not finded
not finded
3
not finded
not finded
not finded
4
not finded
5
6
not finded
not finded
not finded
7
not finded
8
not finded
9
not finded
not finded
10
not finded
not finded
11
not finded
not finded
not finded
12
not finded
13
not finded
not finded
not finded
14
15
not finded
16
not finded
not finded
17
not finded
not finded
not finded
not finded
not finded
18
not finded
not finded
not finded
19
not finded
not finded
Wall time: 4min 8s

In [64]:
btc_direct_table.loc[btc_direct_table.timestamp == 1550793600, :]

      Unnamed: 0  direct   timestamp
1619        1619       1  1550793600

In [ ]:
data = pd.read_csv(f'{folder}/set_133.csv')

In [ ]:
for i in range(14, 40):
    print (i)
    data_add = pd.read_csv(f'{folder}/set_{i}3.csv')
    data = data.append(data_add, sort=False, ignore_index=True)

In [ ]:
data.to_csv(f'{folder}/set_393.csv')