In [2]:
import pandas as pd
import numpy as np
folder = 'd:/git/project1/generated'

In [5]:
df = pd.read_csv(f'{folder}/bts_price_changes.csv')
del df['Unnamed: 0']
df = df.drop(index=[2400])

,Open,High,Low,Close,Volume,change_1_day,change_3_day,change_7_day,change_14_day,change_30_day,change_60_day,change_90_day,change_180_day,timestamp
0,465.864014,468.174011,452.421997,457.334015,2.105680e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1410912000
1,456.859985,456.859985,413.104004,424.440002,3.448320e+07,-9.004029,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1410998400
2,424.102997,427.834991,384.532013,394.795990,3.791970e+07,-32.756988,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1411084800
3,394.673004,423.295990,389.882996,408.903992,3.686360e+07,-29.429993,-71.191010,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1411171200
4,408.084991,412.425995,393.181000,398.821014,2.658010e+07,13.411987,-48.774994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1411257600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2396,58253.777344,61276.664063,58038.707031,59793.234375,5.823847e+10,2226.648437,-845.371094,-772.316406,6643.550781,3502.550781,19439.734375,17537.921875,47030.480469,1618012800
2397,59846.230469,60790.554688,59289.796875,60204.964844,4.628025e+10,-72.785156,67.269531,-1143.632812,3116.210938,2290.597656,12068.785156,17999.558594,58120.811523,1618099200
2398,60175.945313,61253.035156,59589.875000,59893.453125,5.182869e+10,1592.453125,3746.316406,2241.390625,3871.289063,2025.011719,13376.468750,21499.699219,48550.148438,1618185600
2399,60292.875000,63152.812500,59892.859375,62944.847656,6.289527e+10,329.714844,1849.382813,1415.070313,4228.046875,2832.574219,15277.234375,24659.585938,48746.897461,1618272000
2400,451.837402,451.837402,451.837402,451.837402,4.678324e+10,116.929687,2039.097656,1120.941406,2542.742187,-928.257813,12415.839844,26377.753906,48866.272461,1587168000

In [41]:
df

,Open,High,Low,Close,Volume,change_1_day,change_3_day,change_7_day,change_14_day,change_30_day,...,direct_1,direct_3,direct_7,direct_14,direct_30,direct_60,direct_90,direct_180,change_percent_1,change_percent_180
0,465.864014,468.174011,452.421997,457.334015,2.105680e+07,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0.000000,0.000000
1,456.859985,456.859985,413.104004,424.440002,3.448320e+07,-9.004029,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,-0.021214,0.000000
2,424.102997,427.834991,384.532013,394.795990,3.791970e+07,-32.756988,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,-0.082972,0.000000
3,394.673004,423.295990,389.882996,408.903992,3.686360e+07,-29.429993,-71.191010,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,-0.071973,0.000000
4,408.084991,412.425995,393.181000,398.821014,2.658010e+07,13.411987,-48.774994,0.000000,0.000000,0.000000,...,1,0,0,0,0,0,0,0,0.033629,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,58326.562500,58937.046875,57807.863281,58245.003906,4.665521e+10,-2086.593750,-2660.960937,-2826.648437,3373.167969,3826.945313,...,0,0,0,1,1,1,1,1,-0.035824,0.773298
2396,58253.777344,61276.664063,58038.707031,59793.234375,5.823847e+10,2226.648437,-845.371094,-772.316406,6643.550781,3502.550781,...,1,0,0,1,1,1,1,1,0.037239,0.786552
2397,59846.230469,60790.554688,59289.796875,60204.964844,4.628025e+10,-72.785156,67.269531,-1143.632812,3116.210938,2290.597656,...,0,1,0,1,1,1,1,1,-0.001209,0.965382
2398,60175.945313,61253.035156,59589.875000,59893.453125,5.182869e+10,1592.453125,3746.316406,2241.390625,3871.289063,2025.011719,...,1,1,1,1,1,1,1,1,0.026588,0.810609
2399,60292.875000,63152.812500,59892.859375,62944.847656,6.289527e+10,329.714844,1849.382813,1415.070313,4228.046875,2832.574219,...,1,1,1,1,1,1,1,1,0.005238,0.774438

In [42]:
period = 180
df[f'change_percent_{period}'] = df.apply(lambda x: x[f'change_{period}_day']/x['Close'], axis=1)
target = f'direct_{period}'
df[['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume', target]].corr()[target].sort_values()

Volume        0.094758
timestamp     0.134341
Low           0.212345
Open          0.214396
Close         0.214691
High          0.215917
direct_180    1.000000
Name: direct_180, dtype: float64

In [45]:
x_train = np.array(df.loc[:1800,['timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']])
x_train

array([[1.41091200e+09, 4.65864014e+02, 4.68174011e+02, 4.52421997e+02,
        4.57334015e+02, 2.10568000e+07],
       [1.41099840e+09, 4.56859985e+02, 4.56859985e+02, 4.13104004e+02,
        4.24440002e+02, 3.44832000e+07],
       [1.41108480e+09, 4.24102997e+02, 4.27834991e+02, 3.84532013e+02,
        3.94795990e+02, 3.79197000e+07],
       ...,
       [1.56625920e+09, 1.09163467e+04, 1.09470420e+04, 1.06189609e+04,
        1.07632324e+04, 1.50530822e+10],
       [1.56634560e+09, 1.07645723e+04, 1.07987295e+04, 9.96272168e+03,
        1.01380498e+04, 1.94730848e+10],
       [1.56643200e+09, 1.01425215e+04, 1.02329961e+04, 9.83146289e+03,
        1.01310557e+04, 1.70975089e+10]])

In [46]:
x_train = np.array(df.loc[:1800,[target]])
x_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [47]:
import tensorflow
from keras import models
from keras import layers
from keras import regularizers
import matplotlib.pyplot as plt

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint, TensorBoard, ReduceLROnPlateau
weights_file = f'{folder}/weights3.h5'
callback = ModelCheckpoint(weights_file, monitor='val_binary_accuracy', mode='max', save_best_only=True)
tensorboard_cbk = TensorBoard(log_dir=f'{folder}/logs')
reduce = ReduceLROnPlateau(monitor="val_loss", patience=5, min_lr=0.000001, verbose=1)

In [ ]:
model = models.Sequential()

model.add(layers.Dense(384, input_shape=(768,), activity_regularizer=regularizers.l2(0.02), kernel_initializer="he_uniform"))
model.add(layers.BatchNormalization())
model.add(layers.ReLU())

model.add(layers.Dropout(0.5))

model.add(layers.Dense(192, activity_regularizer=regularizers.l2(0.02), kernel_initializer="he_uniform"))
model.add(layers.BatchNormalization())
model.add(layers.ReLU())

model.add(layers.Dense(1, activation='sigmoid'))

#model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['binary_accuracy'])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [ ]:
json_file = f'{folder}/model_btc.json'
model_json = model.to_json()

with open(json_file, 'w') as file:
    file.write(model_json)

In [ ]:
history = model.fit(x_train, y_train, epochs=5, batch_size=2000, validation_split=0.3, callbacks=[callback, tensorboard_cbk, reduce])

In [ ]:
start = 0
loss_values = history.history['loss'][start:]
val_loss_values = history.history['val_loss'][start:]
epochs = range(start, len(loss_values) + start)
plt.plot(epochs, loss_values, 'g', label='Training loss')
plt.plot(epochs, val_loss_values, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

In [ ]:
plt.clf()
acc_values = history.history['binary_accuracy']
val_acc_values = history.history['val_binary_accuracy']
epochs = range(1, len(acc_values) + 1)
plt.plot(epochs, acc_values, 'g', label='Training acc')
plt.plot(epochs, val_acc_values, 'b', label='Validation acc')
plt.title('Training and validation binary_accuracy')
plt.xlabel('Epochs')
plt.ylabel('binary_accuracy')
plt.legend()
plt.show()